### ISSUE TITLE
Domain Settings Are Overwritten

### ISSUE THREAD

**Issue by awickham10** [gomorpheus/morpheus-msdns-plugin#1]
It appears whenever the integration syncs, any domain settings are overwritten. We have enabled joining the domain, providing username/password, and the OU. All of those are get wiped out.

**Comment by davydotcom** [comment]
Looking into this thanks for the feedback!

**Comment by davydotcom** [comment]
Just wanted to confirm, did you download and install this plugin or are you using the existing embedded version of msdns? also what morpheus version 5.5.2?

**Comment by awickham10** [comment]
Yeah, downloaded from the marketplace and was running on 5.5.2.

**Comment by davydotcom** [comment]
Thanks for the feedback! Just released 1.0.1 on the marketplace which should resolve this issue. NOTE: You need to sync at least once for it to correct the dataset. After applying this version simply edit and resave the integration to allow it to sync. Then things should stick. Sorry about that. Looks like a small oversight when converting to plugin form.

**Comment by awickham10** [comment]
Great news, thank you!
